= Cheatsheets

[[BridgeOptions]]
== BridgeOptions

++++
 Specify the event bus bridge options.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[inboundPermitted]]`inboundPermitted`|`Array of link:dataobjects.html#PermittedOptions[PermittedOptions]`|-
|[[inboundPermitteds]]`inboundPermitteds`|`Array of link:dataobjects.html#PermittedOptions[PermittedOptions]`|-
|[[outboundPermitted]]`outboundPermitted`|`Array of link:dataobjects.html#PermittedOptions[PermittedOptions]`|-
|[[outboundPermitteds]]`outboundPermitteds`|`Array of link:dataobjects.html#PermittedOptions[PermittedOptions]`|-
|[[pointToPoint]]`pointToPoint`|`Boolean`|-
|===

[[Frame]]
== Frame

++++
 Represents a STOMP frame. STOMP frames are structured as follows. It starts by a <code>command</code>, followed by a
 set of headers. Then the frame may have a body and is finished by a <code>0</code> byte. This class represents this
 structure and provide access to the different parts.
 <p/>
 This class is <strong>NOT</strong> thread-safe.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[ack]]`ack`|`String`|
+++
Gets the value of the <code>ack</code> header.
+++
|[[body]]`body`|`Buffer`|
+++
Sets the body of the frame.
+++
|[[bodyAsString]]`bodyAsString`|`String`|
+++
Gets the body of the frames as a String encoded in the frame encoding.
+++
|[[command]]`command`|`link:enums.html#Command[Command]`|
+++
Sets the frame command.
+++
|[[destination]]`destination`|`String`|-
|[[headers]]`headers`|`String`|
+++
Gets the frame headers. Modifications to the returned  modifies the headers of the frame.
+++
|[[id]]`id`|`String`|-
|[[receipt]]`receipt`|`String`|-
|[[transaction]]`transaction`|`String`|-
|===

[[PermittedOptions]]
== PermittedOptions

++++
 Specify a match to allow for inbound and outbound traffic.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
The exact address the message is being sent to. If you want to allow messages based on
 an exact address you use this field.
+++
|[[addressRegex]]`addressRegex`|`String`|
+++
A regular expression that will be matched against the address. If you want to allow messages
 based on a regular expression you use this field. If the link value is specified
 this will be ignored.
+++
|===

[[StompServerOptions]]
== StompServerOptions

++++
 STOMP Server options. You can also configure the Net Server used by the STOMP server from these options.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptBacklog]]`acceptBacklog`|`Number (int)`|-
|[[clientAuth]]`clientAuth`|`link:enums.html#ClientAuth[ClientAuth]`|-
|[[clientAuthRequired]]`clientAuthRequired`|`Boolean`|-
|[[crlPaths]]`crlPaths`|`Array of String`|-
|[[crlValues]]`crlValues`|`Array of Buffer`|-
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|-
|[[heartbeat]]`heartbeat`|`Json object`|
+++
Gets the heartbeat configuration. Defaults to <code>x: 1000, y: 1000</code>.
+++
|[[host]]`host`|`String`|-
|[[idleTimeout]]`idleTimeout`|`Number (int)`|-
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|-
|[[maxBodyLength]]`maxBodyLength`|`Number (int)`|
+++
Gets the max length of the frame body accepted by the server. If a frame exceeds this size, the frame is
 rejected and an error is sent to the client.
+++
|[[maxFrameInTransaction]]`maxFrameInTransaction`|`Number (int)`|
+++
Gets the maximum number of frames that can be added to a transaction. If the number of frame added to a
 transaction exceeds this threshold, the client receives an <code>ERROR</code> frame and is disconnected.
+++
|[[maxHeaderLength]]`maxHeaderLength`|`Number (int)`|
+++
Gets the max length of header's value. If a frame has an header with a value exceeding this length, the frame is
 rejected and an error is sent to the client. 10240 by default.
+++
|[[maxHeaders]]`maxHeaders`|`Number (int)`|
+++
Gets the maximum number of headers supported by the server. If a frame exceeds the number of headers, the frame
 is rejected and an error is sent to the client.
+++
|[[maxSubscriptionsByClient]]`maxSubscriptionsByClient`|`Number (int)`|
+++
Gets the maximum of subscriptions a client is allowed to register. If a client exceeds this number, it receives
 an error and the connection is closed.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|-
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|-
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|-
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|-
|[[port]]`port`|`Number (int)`|-
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|-
|[[reuseAddress]]`reuseAddress`|`Boolean`|-
|[[secured]]`secured`|`Boolean`|
+++
Checks whether or not the server is secured (meaning it has an authentication mechanism). Security is disabled
 by default and requires an link handler.
+++
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|-
|[[sendErrorOnNoSubscriptions]]`sendErrorOnNoSubscriptions`|`Boolean`|
+++
Checks whether or not an error is sent to the client when this client sends a message to an not subscribed
 destinations (no subscriptions on this destination).
+++
|[[soLinger]]`soLinger`|`Number (int)`|-
|[[ssl]]`ssl`|`Boolean`|-
|[[supportedVersions]]`supportedVersions`|`Array of String`|
+++
Gets the STOMP protocol versions supported by the server. Versions are provided in the decreasing order. By
 default it's <code>"1.2", "1.1", "1.0"</code>.
+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|-
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|-
|[[timeFactor]]`timeFactor`|`Number (int)`|
+++
Gets the time factor, i.e. a multiplier applied to time constraints as a window error. 1 by default.
+++
|[[trafficClass]]`trafficClass`|`Number (int)`|-
|[[transactionChunkSize]]`transactionChunkSize`|`Number (int)`|
+++
Gets the chunk size when replaying a transaction. To avoid blocking the event loop for too long, large
 transactions are split into chunks, replayed one by one. This settings gets the chunk size.
+++
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|-
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|-
|===

[[StompClientOptions]]
== StompClientOptions

++++
 Options used to configure a STOMP client. As a STOMP client wraps a Net client, you can also configure the
 underlying NET client.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[acceptedVersions]]`acceptedVersions`|`Array of String`|
+++
Gets the list of STOMP protocol versions accepted by the client.
+++
|[[autoComputeContentLength]]`autoComputeContentLength`|`Boolean`|
+++
Whether or not the automatic computation of the <code>content-length</code> header is enabled.
+++
|[[bypassHostHeader]]`bypassHostHeader`|`Boolean`|
+++
Checks whether or not the <code>host</code> header must be dropped from the <code>CONNECT/STOMP</code> frame. Server may
 be picky about this header (such as RabbitMQ that does not support it).
+++
|[[connectTimeout]]`connectTimeout`|`Number (int)`|-
|[[crlPaths]]`crlPaths`|`Array of String`|-
|[[crlValues]]`crlValues`|`Array of Buffer`|-
|[[enabledCipherSuites]]`enabledCipherSuites`|`Array of String`|-
|[[heartbeat]]`heartbeat`|`Json object`|
+++
Gets the heartbeat configuration.
+++
|[[host]]`host`|`String`|
+++
Gets the STOMP server host.
+++
|[[idleTimeout]]`idleTimeout`|`Number (int)`|-
|[[keyStoreOptions]]`keyStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|-
|[[login]]`login`|`String`|
+++
Gets the configured login.
+++
|[[passcode]]`passcode`|`String`|
+++
Gets the configured passcode.
+++
|[[pemKeyCertOptions]]`pemKeyCertOptions`|`link:dataobjects.html#PemKeyCertOptions[PemKeyCertOptions]`|-
|[[pemTrustOptions]]`pemTrustOptions`|`link:dataobjects.html#PemTrustOptions[PemTrustOptions]`|-
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|-
|[[pfxTrustOptions]]`pfxTrustOptions`|`link:dataobjects.html#PfxOptions[PfxOptions]`|-
|[[port]]`port`|`Number (int)`|
+++
Gets the STOMP server port.
+++
|[[receiveBufferSize]]`receiveBufferSize`|`Number (int)`|-
|[[reconnectAttempts]]`reconnectAttempts`|`Number (int)`|-
|[[reconnectInterval]]`reconnectInterval`|`Number (long)`|-
|[[reuseAddress]]`reuseAddress`|`Boolean`|-
|[[sendBufferSize]]`sendBufferSize`|`Number (int)`|-
|[[soLinger]]`soLinger`|`Number (int)`|-
|[[ssl]]`ssl`|`Boolean`|-
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|-
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|-
|[[trafficClass]]`trafficClass`|`Number (int)`|-
|[[trustAll]]`trustAll`|`Boolean`|-
|[[trustStoreOptions]]`trustStoreOptions`|`link:dataobjects.html#JksOptions[JksOptions]`|-
|[[usePooledBuffers]]`usePooledBuffers`|`Boolean`|-
|[[useStompFrame]]`useStompFrame`|`Boolean`|
+++
Checks whether or not the connection is made using the <code>STOMP</code> command instead of the <code>CONNECT</code>
 command. The <code>STOMP</code> command has been introduced in the 1.2 version of the protocol to ease the network
 analysis (as <code>CONNECT</code> is also used by HTTP. To be compliant with server not implementing the 1.2
 specification, this option should be disabled.
+++
|===

