== StompClientOptions

++++
 Options used to configure a STOMP client. As a STOMP client wraps a Net client, you can also configure the
 underlying NET client.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|[[acceptedVersions]]`acceptedVersions`
|`Array of String`
|+++
Sets the list of STOMP protocol versions accepted by the client. The list must be ordered from the lowest
 version to the highest. By default the following list is used: <code>1.0, 1.1, 1.2</code>+++

|[[autoComputeContentLength]]`autoComputeContentLength`
|`Boolean`
|+++
Sets whether or not the automatic computation of the <code>content-length</code> header is enabled. If enabled, the
 <code>content-length</code> header is set in all frame with a body that do not explicitly set the header. The option
 is enabled by default.+++

|[[bypassHostHeader]]`bypassHostHeader`
|`Boolean`
|+++
Sets whether or not the <code>host</code> header must be dropped from the <code>CONNECT/STOMP</code> frame. Server may
 be picky about this header (such as RabbitMQ that does not support it). Options disabled by default.+++

|[[connectTimeout]]`connectTimeout`
|`Number (int)`
|-
|[[crlPaths]]`crlPaths`
|`Array of String`
|-
|[[crlValues]]`crlValues`
|`Array of Buffer`
|-
|[[enabledCipherSuites]]`enabledCipherSuites`
|`Array of String`
|-
|[[heartbeat]]`heartbeat`
|`Json object`
|+++
Sets the heartbeat configuration.+++

|[[host]]`host`
|`String`
|+++
Sets the STOMP server host. <code>0.0.0.0</code> by default.+++

|[[idleTimeout]]`idleTimeout`
|`Number (int)`
|-
|[[keyStoreOptions]]`keyStoreOptions`
|`link:JksOptions.html[JksOptions]`
|-
|[[login]]`login`
|`String`
|+++
Sets the login to use if the STOMP server is secured.+++

|[[passcode]]`passcode`
|`String`
|+++
Sets the passcode to use if the STOMP server is secured.+++

|[[pemKeyCertOptions]]`pemKeyCertOptions`
|`link:PemKeyCertOptions.html[PemKeyCertOptions]`
|-
|[[pemTrustOptions]]`pemTrustOptions`
|`link:PemTrustOptions.html[PemTrustOptions]`
|-
|[[pfxKeyCertOptions]]`pfxKeyCertOptions`
|`link:PfxOptions.html[PfxOptions]`
|-
|[[pfxTrustOptions]]`pfxTrustOptions`
|`link:PfxOptions.html[PfxOptions]`
|-
|[[port]]`port`
|`Number (int)`
|+++
Sets the STOMP server port. <code>61613</code> by default.+++

|[[receiveBufferSize]]`receiveBufferSize`
|`Number (int)`
|-
|[[reconnectAttempts]]`reconnectAttempts`
|`Number (int)`
|-
|[[reconnectInterval]]`reconnectInterval`
|`Number (long)`
|-
|[[reuseAddress]]`reuseAddress`
|`Boolean`
|-
|[[sendBufferSize]]`sendBufferSize`
|`Number (int)`
|-
|[[soLinger]]`soLinger`
|`Number (int)`
|-
|[[ssl]]`ssl`
|`Boolean`
|-
|[[tcpKeepAlive]]`tcpKeepAlive`
|`Boolean`
|-
|[[tcpNoDelay]]`tcpNoDelay`
|`Boolean`
|-
|[[trafficClass]]`trafficClass`
|`Number (int)`
|-
|[[trustAll]]`trustAll`
|`Boolean`
|-
|[[trustStoreOptions]]`trustStoreOptions`
|`link:JksOptions.html[JksOptions]`
|-
|[[usePooledBuffers]]`usePooledBuffers`
|`Boolean`
|-
|[[useStompFrame]]`useStompFrame`
|`Boolean`
|+++
Sets whether or not the connection is made using the <code>STOMP</code> command instead of the <code>CONNECT</code> command.
 The <code>STOMP</code> command has been introduced in the 1.2 version of the protocol to ease the network analysis
 (as <code>CONNECT</code> is also used by HTTP. To be compliant with server not implementing the 1.2 specification,
 this option should be disabled. This option is disabled by default.+++
|===
