= Vert.x-Stomp
:toc: left

STOMP (https://stomp.github.io/index.html) is the Simple (or Streaming) Text Orientated Messaging Protocol.

STOMP
provides an interoperable wire format so that STOMP clients can communicate with any STOMP message broker to
provide easy and widespread messaging interoperability among many languages, platforms and brokers.

Vertx-Stomp is an implementation of a STOMP server and client. You can use the STOMP server with other clients and
use the STOMP client with other servers. The server and the client supports the version 1.0, 1.1 and 1.2 of the
STOMP protocol (see https://stomp.github.io/stomp-specification-1.2.html).

== Using vertx-stomp

To use the Vert.x Stomp server and client, add the following dependency to the _dependencies_ section of your build
descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>{maven-groupId}</groupId>
  <artifactId>{maven-artifactId}</artifactId>
  <version>{maven-version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile {maven-groupId}:{maven-artifactId}:{maven-version}
----


== STOMP server

=== Creating a STOMP server

The simplest way to create an STOMP server, using all default options is as follows:

[source,js]
----
var StompServerHandler = require("vertx-stomp-js/stomp_server_handler");
var Stomp = require("vertx-stomp-js/stomp");
var server = Stomp.createStompServer(vertx).handler(StompServerHandler.create(vertx)).listen();

----

This creates a STOMP server listening on `localhost:61613` that is compliant with the STOMP specification.

You can configure the port and host in the `link:jsdoc/stomp_server-StompServer.html#listen[listen]`
method:

[source,js]
----
var StompServerHandler = require("vertx-stomp-js/stomp_server_handler");
var Stomp = require("vertx-stomp-js/stomp");
var server = Stomp.createStompServer(vertx).handler(StompServerHandler.create(vertx)).listen(1234, "0.0.0.0");

----

To be notified when the server is ready, pass a handler as follows:

[source,js]
----
var StompServerHandler = require("vertx-stomp-js/stomp_server_handler");
var Stomp = require("vertx-stomp-js/stomp");
var server = Stomp.createStompServer(vertx).handler(StompServerHandler.create(vertx)).listen(function (ar, ar_err) {
  if (ar_err != null) {
    console.log("Failing to start the STOMP server : " + ar_err.getMessage());
  } else {
    console.log("Ready to receive STOMP frames");
  }
});

----

You can also pass the host and port in `link:../cheatsheet/StompServerOptions.html[StompServerOptions]`:

[source,js]
----
var StompServerHandler = require("vertx-stomp-js/stomp_server_handler");
var Stomp = require("vertx-stomp-js/stomp");
var server = Stomp.createStompServer(vertx, {
  "port" : 1234,
  "host" : "0.0.0.0"
}).handler(StompServerHandler.create(vertx)).listen();

----

=== Closing a STOMP server

STOMP servers are closed as follows:

[source,js]
----
server.close(function (ar, ar_err) {
  if (ar_err == null) {
    console.log("The STOMP server has been closed");
  } else {
    console.log("The STOMP server failed to close : " + ar_err.getMessage());
  }
});

----

=== Configuration

The `link:../cheatsheet/StompServerOptions.html[StompServerOptions]` let you configure some aspects of the STOMP server.

First, the STOMP server is based on a
`link:../../vertx-core/js/jsdoc/net_server-NetServer.html[NetServer]`, so you can configure the underlying `link:../../vertx-core/js/jsdoc/net_server-NetServer.html[NetServer]` from
the `link:../cheatsheet/StompServerOptions.html[StompServerOptions]`. Alternatively you can also pass the
`link:../../vertx-core/js/jsdoc/net_server-NetServer.html[NetServer]` you want to use:

[source,js]
----
var StompServerHandler = require("vertx-stomp-js/stomp_server_handler");
var Stomp = require("vertx-stomp-js/stomp");
var server = Stomp.createStompServer(vertx, netServer).handler(StompServerHandler.create(vertx)).listen();

----

The `link:../cheatsheet/StompServerOptions.html[StompServerOptions]` let you configure:

* the host and port of the STOMP server - defaults to `0.0.0.0:61613`.
* whether or not the STOMP server is secured - defaults to `false`
* the max STOMP frame body - default to 10 Mb
* the maximum number of headers accepted in a STOMP frame - defaults to 1000
* the max length of a header line in a STOMP frame - defaults to 10240
* the STOMP heartbeat time - default to `1000, 1000`
* the _acknowledgement timeout_ (time before a message is considered not-acknowledged) - default to 10 seconds
* the supported STOMP protocol versions (1.0, 1.1 and 1.2 by default)

The STOMP heartbeat is configured using a JSON object as follows:

[source,js]
----
var StompServerHandler = require("vertx-stomp-js/stomp_server_handler");
var Stomp = require("vertx-stomp-js/stomp");
var server = Stomp.createStompServer(vertx, {
  "heartbeat" : {
    "x" : 1000,
    "y" : 1000
  }
}).handler(StompServerHandler.create(vertx)).listen();

----

Enabling security requires an additional `link:jsdoc/authentication_handler-AuthenticationHandler.html[AuthenticationHandler]` handling the
authentication requests:

[source,js]
----
var Future = require("vertx-js/future");
var StompServerHandler = require("vertx-stomp-js/stomp_server_handler");
var Stomp = require("vertx-stomp-js/stomp");
var server = Stomp.createStompServer(vertx, {
  "secured" : true
}).handler(StompServerHandler.create(vertx).authenticationHandler(function (login, passcode, resultHandler) {
  // Don't reuse this code.
  if ("admin" == login && "admin" == passcode) {
    resultHandler.handle(Future.succeededFuture(true));
  } else {
    resultHandler.handle(Future.succeededFuture(false));
  }
})).listen();

----

If a frame exceeds on of the size limits, the frame is rejected and the client receives an `ERROR` frame. As the
specification requires, the client connection is closed immediately after having sent the error.

=== Subscriptions

The default STOMP server handles subscription destination as opaque Strings. So it does not promote a structure
and it not hierarchic.

=== Acknowledgment

Messages requiring acknowledgment are placed in a queue. If the acknowledgment does not happen in time (the
_acknowledgement timeout_), the message is considered as non-acknowledged. By default, the STOMP server does
nothing (except writing a log message) when a message is not acknowledged. You can customize this using a specific
handler:

[source,js]
----
var StompServerHandler = require("vertx-stomp-js/stomp_server_handler");
var Stomp = require("vertx-stomp-js/stomp");
var server = Stomp.createStompServer(vertx).handler(StompServerHandler.create(vertx).onAckHandler(function (acknowledgement) {
  // Action to execute when the frames (one in `client-individual` mode, several
  // in `client` mode are acknowledged.
}).onNackHandler(function (acknowledgement) {
  // Action to execute when the frames (1 in `client-individual` mode, several in
  // `client` mode are not acknowledged.
})).listen();

----

=== Customizing the STOMP server

In addition to the handlers seen above, you can configure almost all aspects of the STOMP server, such as the
actions made when specific frames are received, the `ping` to sent to the client (to implement the heartbeat).
Here are some examples:

[source,js]
----
var StompServerHandler = require("vertx-stomp-js/stomp_server_handler");
var Stomp = require("vertx-stomp-js/stomp");
var server = Stomp.createStompServer(vertx).handler(StompServerHandler.create(vertx).closeHandler(function (connection) {
  // client connection closed
}).beginHandler(function (frame) {
  // transaction starts
}).commitHandler(function (frame) {
  // transaction committed
})).listen();

----

Be aware that changing the default behavior may break the compliance with the STOMP specification. So, please look
at the default implementations.

== STOMP client

STOMP clients connect to STOMP server and can sends and receive frames.

=== Creating a STOMP client

You create a `link:jsdoc/stomp_client-StompClient.html[StompClient]` instance with default options as follows:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;

  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

the previous snippet creates a STOMP client connecting to "0.0.0.0:61613". Once connected, you get a
`link:jsdoc/stomp_client_connection-StompClientConnection.html[StompClientConnection]` that let you interact with the server. You can
configure the host and port as follows:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx).connect(61613, "0.0.0.0", function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;

  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

Alternatively you can also configure the host and port in the `link:../cheatsheet/StompClientOptions.html[StompClientOptions]`:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx, {
  "host" : "localhost",
  "port" : 1234
}).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;

  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

=== Closing a STOMP client

You can close a STOMP client:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx, {
  "host" : "localhost",
  "port" : 1234
}).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;

  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

client.close();

----

However, this way would not notify the server of the disconnection. To cleanly close the connection, you should
use the `link:jsdoc/stomp_client_connection-StompClientConnection.html#disconnect[disconnect]` method:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx, {
  "host" : "localhost",
  "port" : 1234
}).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;

    connection.disconnect();
  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

If the heartbeat is enabled and if the client did not detect server activity after the configured timeout, the
connection is automatically closed.

=== Handling errors

On the `link:jsdoc/stomp_client_connection-StompClientConnection.html[StompClientConnection]`, you can register an error handler receiving `ERROR`
frames sent by the server. Notice that the server closes the connection with the client after having sent such frame:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx, {
  "host" : "localhost",
  "port" : 1234
}).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;
    connection.errorHandler(function (frame) {
      console.log("ERROR frame received : " + frame);
    });
  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

=== Configuration

You can configure various aspect by passing a
`link:../cheatsheet/StompClientOptions.html[StompClientOptions]` when creating the `link:jsdoc/stomp_client-StompClient.html[StompClient]`. As the
STOMP client relies on a `link:../../vertx-core/js/jsdoc/net_client-NetClient.html[NetClient]`, you can configure the underlying Net Client from
the `link:../cheatsheet/StompClientOptions.html[StompClientOptions]`. Alternatively, you can pass the `link:../../vertx-core/js/jsdoc/net_client-NetClient.html[NetClient]`
you want to use in the
`link:jsdoc/stomp_client-StompClient.html#connect[connect]` method:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx).connect(netClient, function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;
    connection.errorHandler(function (frame) {
      console.log("ERROR frame received : " + frame);
    });
  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

The `link:../cheatsheet/StompClientOptions.html[StompClientOptions]` let you configure:

* the host and port ot the STOMP server
* the login and passcode to connect to the server
* whether or not the `content-length` header should be added to the frame if not set explicitly. (enabled by default)
* whether or not the `STOMP` command should be used instead of the `CONNECT` command (disabled by default)
* whether or not the `host` header should be ignored in the `CONNECT` frame (disabled by default)
* the heartbeat configuration (1000, 1000 by default)

=== Subscribing to destinations

To subscribe to a destination, use:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;
    connection.subscribe("/queue", function (frame) {
      console.log("Just received a frame from /queue : " + frame);
    });
  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

To unsubscribe, use:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;
    connection.subscribe("/queue", function (frame) {
      console.log("Just received a frame from /queue : " + frame);
    });

    // ....

    connection.unsubscribe("/queue");
  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

=== Sending messages

To send a message, use:

[source,js]
----
var Buffer = require("vertx-js/buffer");
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;
    var headers = {};
    headers["header1"] = "value1";
    connection.send("/queue", headers, Buffer.buffer("Hello"));
    // No headers:
    connection.send("/queue", Buffer.buffer("World"));
  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----



=== Acknowledgements

Clients can send `ACK` and `NACK` frames:

[source,js]
----
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;
    connection.subscribe("/queue", function (frame) {
      connection.ack(frame);
      // OR
      connection.nack(frame);
    });
  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

=== Transactions

Clients can also create transactions. `ACK`, `NACK` and `SEND` frames sent in the transaction will be delivery
only when the transaction is committed.

[source,js]
----
var Buffer = require("vertx-js/buffer");
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;
    var headers = {};
    headers["transaction"] = "my-transaction";
    connection.beginTX("my-transaction");
    connection.send("/queue", headers, Buffer.buffer("Hello"));
    connection.send("/queue", headers, Buffer.buffer("World"));
    connection.send("/queue", headers, Buffer.buffer("!!!"));
    connection.commit("my-transaction");
    // OR
    connection.abort("my-transaction");
  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----

=== Receipt

Each sent commands can have a _receipt_ handler, notified when the server has processed the message:

[source,js]
----
var Buffer = require("vertx-js/buffer");
var Stomp = require("vertx-stomp-js/stomp");
var client = Stomp.createStompClient(vertx).connect(function (ar, ar_err) {
  if (ar_err == null) {
    var connection = ar;

    connection.send("/queue", Buffer.buffer("Hello"), function (frame) {
      console.log("Message processed by the server");
    });
  } else {
    console.log("Failed to connect to the STOMP server: " + ar_err.toString());
  }
});

----