= Vert.x-Stomp
:toc: left

STOMP (https://stomp.github.io/index.html) is the Simple (or Streaming) Text Orientated Messaging Protocol.

STOMP
provides an interoperable wire format so that STOMP clients can communicate with any STOMP message broker to
provide easy and widespread messaging interoperability among many languages, platforms and brokers.

Vertx-Stomp is an implementation of a STOMP server and client. You can use the STOMP server with other clients and
use the STOMP client with other servers. The server and the client supports the version 1.0, 1.1 and 1.2 of the
STOMP protocol (see https://stomp.github.io/stomp-specification-1.2.html).

== Using vertx-stomp

To use the Vert.x Stomp server and client, add the following dependency to the _dependencies_ section of your build
descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>{maven-groupId}</groupId>
  <artifactId>{maven-artifactId}</artifactId>
  <version>{maven-version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile {maven-groupId}:{maven-artifactId}:{maven-version}
----


== STOMP server

=== Creating a STOMP server

The simplest way to create an STOMP server, using all default options is as follows:

[source,java]
----
StompServer server = Stomp.createStompServer(vertx)
    .handler(StompServerHandler.create(vertx))
    .listen();
----

This creates a STOMP server listening on `localhost:61613` that is compliant with the STOMP specification.

You can configure the port and host in the `link:../../apidocs/io/vertx/ext/stomp/StompServer.html#listen-int-java.lang.String-[listen]`
method:

[source,java]
----
StompServer server = Stomp.createStompServer(vertx)
    .handler(StompServerHandler.create(vertx))
    .listen(1234, "0.0.0.0");
----

To be notified when the server is ready, pass a handler as follows:

[source,java]
----
StompServer server = Stomp.createStompServer(vertx)
    .handler(StompServerHandler.create(vertx))
    .listen(ar -> {
      if (ar.failed()) {
        System.out.println("Failing to start the STOMP server : " + ar.cause().getMessage());
      } else {
        System.out.println("Ready to receive STOMP frames");
      }
    });
----

You can also pass the host and port in `link:../../apidocs/io/vertx/ext/stomp/StompServerOptions.html[StompServerOptions]`:

[source,java]
----
StompServer server = Stomp.createStompServer(vertx, new StompServerOptions().setPort(1234).setHost("0.0.0.0"))
    .handler(StompServerHandler.create(vertx))
    .listen();
----

=== Closing a STOMP server

STOMP servers are closed as follows:

[source,java]
----
server.close(ar -> {
  if (ar.succeeded()) {
    System.out.println("The STOMP server has been closed");
  } else {
    System.out.println("The STOMP server failed to close : " + ar.cause().getMessage());
  }
});
----

=== Configuration

The `link:../../apidocs/io/vertx/ext/stomp/StompServerOptions.html[StompServerOptions]` let you configure some aspects of the STOMP server.

First, the STOMP server is based on a
`link:../../apidocs/io/vertx/core/net/NetServer.html[NetServer]`, so you can configure the underlying `link:../../apidocs/io/vertx/core/net/NetServer.html[NetServer]` from
the `link:../../apidocs/io/vertx/ext/stomp/StompServerOptions.html[StompServerOptions]`. Alternatively you can also pass the
`link:../../apidocs/io/vertx/core/net/NetServer.html[NetServer]` you want to use:

[source,java]
----
StompServer server = Stomp.createStompServer(vertx, netServer)
    .handler(StompServerHandler.create(vertx))
    .listen();
----

The `link:../../apidocs/io/vertx/ext/stomp/StompServerOptions.html[StompServerOptions]` let you configure:

* the host and port of the STOMP server - defaults to `0.0.0.0:61613`.
* whether or not the STOMP server is secured - defaults to `false`
* the max STOMP frame body - default to 10 Mb
* the maximum number of headers accepted in a STOMP frame - defaults to 1000
* the max length of a header line in a STOMP frame - defaults to 10240
* the STOMP heartbeat time - default to `1000, 1000`
* the _acknowledgement timeout_ (time before a message is considered not-acknowledged) - default to 10 seconds
* the supported STOMP protocol versions (1.0, 1.1 and 1.2 by default)

The STOMP heartbeat is configured using a JSON object as follows:

[source,java]
----
StompServer server = Stomp.createStompServer(vertx, new StompServerOptions().setHeartbeat(
    new JsonObject().put("x", 1000).put("y", 1000)))
    .handler(StompServerHandler.create(vertx))
    .listen();
----

Enabling security requires an additional `link:../../apidocs/io/vertx/ext/stomp/AuthenticationHandler.html[AuthenticationHandler]` handling the
authentication requests:

[source,java]
----
StompServer server = Stomp.createStompServer(vertx, new StompServerOptions().setSecured(true))
    .handler(StompServerHandler.create(vertx).authenticationHandler(
        (login, passcode, resultHandler) -> {
          // Don't reuse this code.
          if ("admin".equals(login) && "admin".equals(passcode)) {
            resultHandler.handle(Future.succeededFuture(true));
          } else {
            resultHandler.handle(Future.succeededFuture(false));
          }
        }))
    .listen();
----

If a frame exceeds on of the size limits, the frame is rejected and the client receives an `ERROR` frame. As the
specification requires, the client connection is closed immediately after having sent the error.

=== Subscriptions

The default STOMP server handles subscription destination as opaque Strings. So it does not promote a structure
and it not hierarchic.

=== Acknowledgment

Messages requiring acknowledgment are placed in a queue. If the acknowledgment does not happen in time (the
_acknowledgement timeout_), the message is considered as non-acknowledged. By default, the STOMP server does
nothing (except writing a log message) when a message is not acknowledged. You can customize this using a specific
handler:

[source,java]
----
StompServer server = Stomp.createStompServer(vertx)
    .handler(StompServerHandler.create(vertx)
        .onAckHandler(acknowledgement -> {
          // Action to execute when the frames (one in `client-individual` mode, several
          // in `client` mode are acknowledged.
        })
        .onNackHandler(acknowledgement -> {
          // Action to execute when the frames (1 in `client-individual` mode, several in
          // `client` mode are not acknowledged.
        }))
    .listen();
----

=== Customizing the STOMP server

In addition to the handlers seen above, you can configure almost all aspects of the STOMP server, such as the
actions made when specific frames are received, the `ping` to sent to the client (to implement the heartbeat).
Here are some examples:

[source,java]
----
StompServer server = Stomp.createStompServer(vertx)
    .handler(StompServerHandler.create(vertx)
            .closeHandler(connection -> {
              // client connection closed
            })
            .beginHandler(frame -> {
              // transaction starts
            })
            .commitHandler(frame -> {
                  // transaction committed
                }
            )
        //...
    ).listen();
----

Be aware that changing the default behavior may break the compliance with the STOMP specification. So, please look
at the default implementations.

== STOMP client

STOMP clients connect to STOMP server and can sends and receive frames.

=== Creating a STOMP client

You create a `link:../../apidocs/io/vertx/ext/stomp/StompClient.html[StompClient]` instance with default options as follows:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx)
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();

      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

the previous snippet creates a STOMP client connecting to "0.0.0.0:61613". Once connected, you get a
`link:../../apidocs/io/vertx/ext/stomp/StompClientConnection.html[StompClientConnection]` that let you interact with the server. You can
configure the host and port as follows:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx)
    .connect(61613, "0.0.0.0", ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();

      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

Alternatively you can also configure the host and port in the `link:../../apidocs/io/vertx/ext/stomp/StompClientOptions.html[StompClientOptions]`:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx, new StompClientOptions().setHost("localhost").setPort(1234))
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();

      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

=== Closing a STOMP client

You can close a STOMP client:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx, new StompClientOptions().setHost("localhost").setPort(1234))
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();

      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });

client.close();
----

However, this way would not notify the server of the disconnection. To cleanly close the connection, you should
use the `link:../../apidocs/io/vertx/ext/stomp/StompClientConnection.html#disconnect--[disconnect]` method:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx, new StompClientOptions().setHost("localhost").setPort(1234))
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();

        connection.disconnect();
      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

If the heartbeat is enabled and if the client did not detect server activity after the configured timeout, the
connection is automatically closed.

=== Handling errors

On the `link:../../apidocs/io/vertx/ext/stomp/StompClientConnection.html[StompClientConnection]`, you can register an error handler receiving `ERROR`
frames sent by the server. Notice that the server closes the connection with the client after having sent such frame:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx, new StompClientOptions().setHost("localhost").setPort(1234))
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();
        connection.errorHandler(frame -> System.out.println("ERROR frame received : " + frame));
      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

=== Configuration

You can configure various aspect by passing a
`link:../../apidocs/io/vertx/ext/stomp/StompClientOptions.html[StompClientOptions]` when creating the `link:../../apidocs/io/vertx/ext/stomp/StompClient.html[StompClient]`. As the
STOMP client relies on a `link:../../apidocs/io/vertx/core/net/NetClient.html[NetClient]`, you can configure the underlying Net Client from
the `link:../../apidocs/io/vertx/ext/stomp/StompClientOptions.html[StompClientOptions]`. Alternatively, you can pass the `link:../../apidocs/io/vertx/core/net/NetClient.html[NetClient]`
you want to use in the
`link:../../apidocs/io/vertx/ext/stomp/StompClient.html#connect-io.vertx.core.net.NetClient-io.vertx.core.Handler-[connect]` method:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx)
    .connect(netClient, ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();
        connection.errorHandler(frame -> System.out.println("ERROR frame received : " + frame));
      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

The `link:../../apidocs/io/vertx/ext/stomp/StompClientOptions.html[StompClientOptions]` let you configure:

* the host and port ot the STOMP server
* the login and passcode to connect to the server
* whether or not the `content-length` header should be added to the frame if not set explicitly. (enabled by default)
* whether or not the `STOMP` command should be used instead of the `CONNECT` command (disabled by default)
* whether or not the `host` header should be ignored in the `CONNECT` frame (disabled by default)
* the heartbeat configuration (1000, 1000 by default)

=== Subscribing to destinations

To subscribe to a destination, use:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx)
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();
        connection.subscribe("/queue",
            frame -> System.out.println("Just received a frame from /queue : " + frame));
      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

To unsubscribe, use:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx)
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();
        connection.subscribe("/queue",
            frame -> System.out.println("Just received a frame from /queue : " + frame));

        // ....

        connection.unsubscribe("/queue");
      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

=== Sending messages

To send a message, use:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx)
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();
        Map<String, String> headers = new HashMap<>();
        headers.put("header1", "value1");
        connection.send("/queue", headers, Buffer.buffer("Hello"));
        // No headers:
        connection.send("/queue", Buffer.buffer("World"));
      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

In Java and Groovy, you can use the `link:../../apidocs/io/vertx/ext/stomp/utils/Headers.html[Headers]` class to ease the header creation.


=== Acknowledgements

Clients can send `ACK` and `NACK` frames:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx)
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();
        connection.subscribe("/queue", frame -> {
          connection.ack(frame);
          // OR
          connection.nack(frame);
        });
      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

=== Transactions

Clients can also create transactions. `ACK`, `NACK` and `SEND` frames sent in the transaction will be delivery
only when the transaction is committed.

[source,java]
----
StompClient client = Stomp.createStompClient(vertx)
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();
        Map<String, String> headers = new HashMap<>();
        headers.put("transaction", "my-transaction");
        connection.begin("my-transaction");
        connection.send("/queue", headers, Buffer.buffer("Hello"));
        connection.send("/queue", headers, Buffer.buffer("World"));
        connection.send("/queue", headers, Buffer.buffer("!!!"));
        connection.commit("my-transaction");
        // OR
        connection.abort("my-transaction");
      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----

=== Receipt

Each sent commands can have a _receipt_ handler, notified when the server has processed the message:

[source,java]
----
StompClient client = Stomp.createStompClient(vertx)
    .connect(ar -> {
      if (ar.succeeded()) {
        StompClientConnection connection = ar.result();

        connection.send("/queue", Buffer.buffer("Hello"),
            frame -> {
              System.out.println("Message processed by the server");
            }
        );
      } else {
        System.out.println("Failed to connect to the STOMP server: " + ar.cause().toString());
      }
    });
----